### ISSUE TITLE
Unable to pass page options to PhantomJS

### ISSUE THREAD

**Issue by magoni** [jonkemp/gulp-qunit#24]
My project's QUnit tests require the PhantomJS viewport to be a certain size. I would normally achieve this by setting `viewportSize` on the PhantomJS `page` object in my test runner script like so:

```js
var page = require('webpage').create();
page.viewportSize = { width: 1280, height: 800 };
page.open(url, function(status){
    // ...
```

Currently, setting page options is impossible with `gulp-qunit`, as PhantomJS does not allow this type of thing to be set from the command line options (and so we can't set them via `'phantomjs-options'`). Taking inspiration from https://github.com/gruntjs/grunt-lib-phantomjs, it would be ideal to allow the user to supply an object of options to be set on phantom's page object from within our gulp task.

Maybe the user could do something like this:
```js
gulp.task('test', ['develop:build'], function () {
    return gulp.src('./tests/index.html')
        .pipe(qunit({
            'page': {
                viewportSize: { width: 1280, height: 800 }
            }
        }));
});
```

I would be willing to submit a pull request with tests. This would require some implementation on https://github.com/jonkemp/qunit-phantomjs-runner as well, as far as I can tell.

**Comment by backflip** [comment]
I submitted a pull request to `qunit-phantomjs-runner` after stumbling over the same issue. If merged, we could add the following code to https://github.com/jonkemp/gulp-qunit/blob/master/index.js#L33:

```
if (options.page) {
    // Push default timeout value unless specified otherwise
    if (!options.timeout) {
        childArgs.push(5);
    }

    childArgs.push(JSON.stringify(options.page));
}
```

**Comment by jpgcode** [comment]
Hi all! Any update on this? I'm running exactly the same issue :(

**Comment by jpgcode** [comment]
Using @backflip fork for my project for now. Please update the main module.

**Comment by jonkemp** [comment]
`qunit-phantomjs-runner` pull request was accepted and published. I am trying to get to this as soon as possible, but if anyone that needs this has some time, pull requests are encouraged.

**Comment by jonkemp** [comment]
Done. Please update to v1.4.0.

**Comment by backflip** [comment]
Thanks a lot!
