### ISSUE TITLE
npm v3.0.0

### ISSUE THREAD

**Issue by rioki** [jonkemp/gulp-qunit#26]
Under NPM 3.0.0 the test fails with:

     Can't open 'E:\Development\GitHub\rgm.js\node_modules\gulp-qunit\node_modules\qunit-phantomjs-runner\runner-json.js'

This is the same problem as jonkemp/node-qunit-phantomjs#15.

**Comment by SteveEdson** [comment]
Also getting the same issue. The only thing I changed was switching to Node V5 and NPM 3

**Comment by SteveEdson** [comment]
Thanks for the quick fix. Works great :+1:
